name: Build

on:
  push:
  pull_request:

  # Run automatically every monday
  schedule:
    - cron: 1 12 * * 1

env:
  BUILD_TYPE: Release

jobs:
  host:
    strategy:
      matrix:
        os: ['windows-latest']

      # Don't cancel all builds when one fails
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies (macOS)
      run: brew install fftw
      if: matrix.os == 'macos-latest'

    - name: Install dependencies (Ubuntu)
      run: |
        sudo apt update
        sudo apt install libfftw3-dev libusb-1.0-0-dev
      if: matrix.os == 'ubuntu-latest'

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/host/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/host/build
      run: cmake $GITHUB_WORKSPACE/host/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/host/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
